#Glossary values for tool

stressor_preamb <- paste(h4("Stressors"),
  
  p(em("Stressors are external stimuli that can cause changes to the behavioral, physical, chemical, and/or biological characteristics of an organism, species, or the ecosystem inhabited by the organism/species. In the case of fisheries, stressors are unintended consequences of offshore wind energy development activities that potentially affect fishing and fisheries. While stressors can occur in the natural environment or from human activities, in this case the New York State Energy Research and Development Authority (NYSERDA) is focusing on anthropogenic stressors associated with offshore wind energy development on the Outer Continental Shelf (not in state waters or the cable interconnect to land).")),
  
  p(em("NYSERDA has endeavored to include all stressors that could occur within federal offshore wind lease areas. Section 1.1.1 defines stressors that affect birds and bats, marine mammals and sea turtles, fish, fisheries and/or benthos while Section
1.1.2 includes stressors specific to fisheries.")))


stressor_defs <- 
  
  paste(
    paste(
      p(
        strong("Bottom Disturbance."),
        "Bottom disturbance is physical change to the substrate as a result of wind farm activities, such as packing down sediment with piles or digging up sediment with anchors or jet plows. Changes in turbidity (i.e., amount of suspended particles in water) are considered water quality changes and are not included in bottom disturbance. Displacement of sediment around a structure is considered scouring, and is not included in bottom disturbance."
      )
    ),
    
    paste(
      p(
        strong("Changes in Vessel Traffic."),
        "Changes in vessel traffic include changes in vessel abundance, densities, types, and routes compared to what currently exist, due to activities relating to the offshore wind facility or to displacement of other vessel operations as a result of offshore wind facility activities. This includes, but is not limited to, vessels operating in pre-construction site assessment surveys, construction activities, and maintenance activities. This also includes changes in fishing or shipping patterns in response to wind farm activities."
      )
    ),
    
    paste(
      p(
        strong("EMF, Vibration, and Heat."),
        "Electromagnetic fields (EMF) can be generated by the cables that carry electricity from and between energy sources to power stations and may produce local distortions in Earth’s main electric and magnetic fields. Vibration is an oscillation of parts of a fluid. Vibration can result in particle motion, which is detectable by some marine organisms. Although sound usually has a vibratory component, it differs from vibration in general in that sound also contains a waveform and is perceived by hearing organs; sound is not included in this category. Heat is an increase in water or air temperature above typical levels."
      )
    ),
    
    paste(
      p(
        strong("Light."),
        "Light is artificial light produced by, or in relation to, the offshore wind energy development at a project site. Artificial light produces a luminescence that is brighter or different in color than natural light occurring at the site during the period in question. Examples include lights on vessels, construction equipment, turbines, and other infrastructure to aid in navigation and construction, among other purposes."
      )
    ),
    
    paste(
      p(
        strong("Long-term Structures."),
        "Long-term structures are objects added to the environment that occupy physical space and are present for longer than the construction period. Examples of long-term structures include offshore wind turbines, foundations, scour protection, substations, and other infrastructure associated with the operational wind facility. This term may also apply to the pre- construction phase in the case of meteorological towers, and to the decommissioning phase in the case of any below-water (e.g., foundations) or subsurface (e.g., cables) infrastructure that may be left in place after the towers have been removed. Displacement of sediment around a structure is considered scouring, and is not included in long-term structures."
      )
    ),
    
    paste(
      p(
        strong("Scouring."),
        "Scouring is a physical process related to the movement of seabed sediment around a structure due to its presence, which causes changes in wave or current flows, and results in a reduction in seabed levels around the structure."
      )
    ),
    
    paste(
      p(
        strong("Sound."),
        "Sound is created by a vibrating object and travels as a pressure wave through a medium, and these pressure waves can be sensed by organisms using hearing organs. Activities that produce sound include, but are not limited to, exploratory surveys, pile driving, dredging, and vessel operation. Vibrations that are not related to sound are considered in the Electromagnetic Fields (EMF), Vibration, and Heat stressor category."
      )
    ),
    
    paste(
      p(
        strong("Water Quality Changes."),
        "Water quality is a description of the chemical, physical, and biological characteristics of water as it relates to the health of an organism or ecosystem within the marine environment. Examples of changes in water quality include, but are not limited to, changes in turbidity (amount of suspended particles in water), addition of chemicals (e.g., antifouling paint or oil),and changes in dissolved oxygen (e.g., reductions in oxygen due to warming of the water)."
      )
    )
  )

pot_effects_preamb <- paste(h4("Potential effects"),
                            
    p(em("Potential effectsare the changes to the behavioral, physical, chemical, and/or bio- logical characteristics of an organism, species, or the ecosystem inhabited by the organism/species due to stressors related to offshore wind energy development. In the context of fisheries, potential effects are impacts on fishing activities and revenue as a result of stressors related to offshore wind energy development. Addi- tionally, changes in fishing effort, grounds, and revenue can result from changing markets, ocean conditions, permit and licensing requirements, protected species interactions, natural fish abundance and distribution patterns, and other factors un- related to offshore wind energy development. For purposes of describing potential mitigation practices to address effects of stressors on fisheries, effects are considered outcomes that are a result of offshore wind energy development and not other biological, physical, and economic factors that affect fisheries.
")))


pot_effects_defs <-
  
  paste(
    paste(
      p(
        strong("Behavioral Disturbance."),
        "Behavioral disturbance is a change in individual or group short-term natural behavior (e.g., localized movement patterns, alertness) or behavior patterns (e.g., change from spawning, feeding behavior, or social behavior to another behavior pattern) as a result of a stressor(s), not including changes that would constitute displacement/barrier effects and attraction (listed separately below)."
      )
    ),
    
    paste(
      p(
        strong("Displacement."),
        "Displacement is avoidance of an area associated with offshore wind energy development by individuals or groups as a result of a stressor(s).
This can include short- or long-term effective loss of offshore habitat (such as foraging or roosting grounds, calving/spawning grounds, and above- or below- water movement areas). This also includes barrier effects, in which individuals may alter local or long-distance movements to avoid aspects of offshore wind energy development (including offshore infrastructure and vessel traffic)."
      )
    ),
    
    paste(
      p(
        strong("Attraction."),
        "The movement of individuals or groups toward areas associated with offshore wind energy development in response to a stressor (e.g., attraction to a light source on a wind turbine). This can be caused by sensory attractants or other attractants such as increased prey availability, ways to avoid predators, or changes in other resources."
      )
    ),
    
    paste(
      p(
        strong("Habitat Fragmentation/Modification."),
        "Habitat fragmentation is the loss of habitat that results in division of large, contiguous habitats into smaller disconnected habitat patches. Habitat modification is the change in size, composition, structure, or function of an existing habitat (e.g., wind turbines provide new substrate that can support encrusting organisms that would not otherwise be present in the same numbers or species composition)."
      )
    ),
    
    paste(
      p(
        strong("Injury/Mortality."),
        "Injury includes physical damage to the body, internal or external, permanent or temporary, as well as physiological changes (e.g., stress) that may or may not be expected to lead to death. Mortality is death of an organism."
      )
    ),
    
    paste(
      p(
        strong("Community Alteration/Invasive Species."),
        "Community alteration is a permanent) change to the composition, structure, or function of an ecological community (a group of populations of multiple species occupying the same geographic area at the same time). Invasive species are non-native species that are introduced into a new environment as a result of offshore wind energy development and cause ecological and/or economic harm."
      )
    ),
    
    paste(
      p(
        strong("Change in Fishing Effort."),
        "Change in fishing effort is short- or long-term change in common fishing patterns in time and space, including fishing outside typical fishing grounds, increased effort and/or competition among fishing vessels at available fishing areas, and changes in the numbers of fishing vessels or fisheries in a given area as result of offshore wind energy development."
      )
    ),
    
    paste(
      p(
        strong("Loss of Fishing Revenue."),
        "Loss of revenue is reduced fisheries revenue from typical baseline or expected ranges due to offshore wind energy development.
Loss of revenue can result from loss of gear, damaged gear, reduced catch, additional fuel and other operations costs, etc. Changes in fishing effort due to offshore wind energy development may be accompanied by loss of revenue, but in some cases, revenue may not be affected within normal and/or expected ranges despite changes in fisheries."
      )
    )
  )

dev_phase_preamb <- 
  
  paste(h4("Development phase"),
                            
      p(em("Development phases are the stages of offshore wind facility development/operation, each of which encompass a number of activities and, as a result, may have different types of stressors. mitigation practices are likely to be implemented by development phase.")))

dev_phase_defs <- 
  
  paste(paste(
    p(
      strong("Pre-construction."),
      "This phase includes site assessment work such as geotechnical and geophysical surveys, installation of meteorological towers or buoys, and environmental or other surveys."
    )
  ),
  
  paste(
    p(
      strong("Construction."),
      "This phase, which can last for several years, includes various activities associated with building the turbines and connecting them to the electrical grid, including jack-up barges and other vessel activity. Construction also includes installation of undersea cables among turbines and sub-stations."
    )
  ),
  
  paste(
    p(
      strong("Operations & Maintenance."),
      "This phase, which can last 25 years or more, is the period in which turbines are generating electricity and includes activities relating to turbine monitoring and maintenance."
    )
  ),
  
  paste(
    p(
      strong("Decommissioning."),
      "This phase includes decommissioning activities chosen for a given project site, which may include full removal of structures, removal of above-water structures (to a certain water depth to avoid navigational hazards), or repowering."
    )
  ))

industry_preamb <- paste(h4("Industry terms"),
        
  p(em("Industry terms define the type of industry for which mitigation practices have been suggested or implemented in the U.S. or other countries.")))

industry_defs <-
  
  paste(paste(
    p(
      strong("Offshore Wind."),
      "Offshore wind refers to any offshore wind energy development in marine or freshwater (e.g., Great Lakes) locations."
    )
  ),
  
  paste(
    p(
      strong("Onshore Wind."),
      "Onshore wind refers to wind energy development in terrestrial locations."
    )
  ),
  
  paste(
    p(
      strong("Oil and Gas."),
      "Oil and gas includes both onshore and offshore oil and gas development."
    )
  ),
  
  paste(
    p(
      strong("Maritime."),
      "Maritime refers to any marine or freshwater activity other than offshore wind and oil & gas. This includes shipping, fisheries, transmission, and other industries that operate in the marine environment."
    )
  ),
  
  paste(
    p(
      strong("Generic/General."),
      "Generic/general includes any industry that is not included in the above options, or situations where an industry was not specified."
    )
  ))

implement_status_preamb <- paste(h4("Implementation status"),
        
  p(em("The implementation status defines the degree to which the use or efficacy of a mitigation practice has been tested.")))

implement_status_defs <-
  
  paste(paste(
    p(
      strong("Not Implemented."),
      "Not implemented means that the mitigation practice was not implemented in the source literature."
    )
  ),
  
  paste(
    p(
      strong("Field Tested."),
      "Field tested refers to a situation in which an mitigation practice has not been implemented in a real-world development situation but has been tested in another way, such as academic research or prototypes."
    )
  ),
  
  paste(
    p(
      strong("Implemented."),
      "Implemented means that the mitigation practice was implemented in the source literature, but there was no testing or assessment indicated as to whether it was effective at reducing impacts on the resource of interest."
    )
  ),
  
  paste(
    p(
      strong("Implemented and Evidence of Effectiveness."),
      "Implemented and evidence of effectiveness means that the mitigation practice was (1) implemented in the source literature, and (2) found to be effective when tested or assessed for effectiveness at reducing impacts on the resource of interest."
    )
  ),
  
  paste(
    p(
      strong("Unknown."),
      "Unknown means that, based on source literature, it is unclear whether or not the mitigation practice was implemented."
    )
  ))

mit_heir_preamb <- paste(h4("Mitigation hierarchy"),
        
        p(em("The most applicable level(s) of the mitigation hierarchy was(were) chosen for each mitigation practice. For mitigation practices that were solely monitoring recommendations, no mitigation hierarchy levels were chosen.")))

mit_heir_defs <-
  
  paste(paste(
    p(
      strong("Avoidance."),
      "Avoidance will eliminate impacts entirely. For example, siting a project outside the range of an animal completely avoids impacts on that animal. As another example, operating equipment outside the hearing range of an animal avoids sound impacts on that animal."
    )
  ),
  
  paste(
    p(
      strong("Minimization."),
      "Minimization will reduce the impacts. For example, sound dampening technology may reduce the amount of sound, thus reducing the impact of sound on organisms."
    )
  ),
  
  paste(
    p(
      strong("Restoration."),
      "Restoration refers to measures taken to improve or rehabilitate ecosystem components that are impacted by the project. For example, if a met tower were placed in a mesophotic coral area and after removal of the tower, coral was transplanted back to the area."
    )
  ),
  
  paste(
    p(
      strong("Offset."),
      "Offset is compensation for impacts. For example, monetary compensation could be provided for loss of fishery access. As another example, improvement of off-site habitat or establishment of a marine protected area in another place could offset degradation of habitat in the project area. (Restoration defined above requires restoration of areas directly impacted by the project; other rehabilitation or preservation efforts are offsets typically described as compensatory mitigation)."
    )
  ))

gen_mitpractices_preamb <- paste(h4("Mitigation Type"),
        
        p(em("Categories or types of mitigation practices identified during literature review.")))

gen_mitpractices_defs <-
  paste(
    paste(
      p(
        strong("Barriers."),
        "Barriers include mitigation practices that include physical creation of an obstacle to prevent a stressor (e.g., sound, EMF) from propagating (e.g., bubble curtains to block sound, cable burial to block EMF, scour protection to block sediment movement)."
      )
    ),
    
    paste(
      p(
        strong("Siting/Seasonality."),
        "Siting and seasonality include mitigation practices that consider geographic location choices for long-term wind farm structures (e.g., macro- siting) and/or time of year in activities, including vessel activities. Micro-siting of turbines is considered a structure configuration mitigation practice rather than siting/seasonality."
      )
    ),
    
    paste(
      p(
        strong("Shutdown/Low Power."),
        "Shutdown and low power include mitigation practices that require stopping or reducing the power of an activity (e.g., shutdown of geophysical surveys when marine mammals are present, soft-start pile driving). This also includes curtailment of turbine operations but not feathering or increasing cut-in speed, which are included in turbine operation parameters."
      )
    ),
    
    paste(
      p(
        strong("Vessel Operation Parameters."),
        "Vessel operation parameters include mitigation practices that involve choices in vessel number, behavior, location, direction, equipment, and actions of vessel crew (e.g., positioning vessels with thrusters, educating crew to avoid whale collisions). Vessel location choices are different than siting choices for structures or seasonal activities (see Siting/Seasonality). This is also different from shutdown/low power. If equipment on a vessel is being shut down or run at low power (e.g., shutdown of an echosounder), it is considered a shutdown/low power mitigation practice rather than a vessel operation parameter."
      )
    ),
    
    paste(
      p(
        strong("Limit an Activity."),
        "Limit an activity includes mitigation practices that do not fall into other categories and include a restriction in activity (e.g., avoiding pile driving at night, not using explosives)."
      )
    ),
    
    paste(
      p(
        strong("Structure Configuration."),
        "Structure configuration includes mitigation practices that involve choices in turbine numbers and sizes, foundation types, and how turbines are arranged in space (e.g., micro-siting)."
      )
    ),
    
    paste(
      p(
        strong("Water Quality Management."),
        "Water quality management includes mitigation practices that are designed to avoid water quality impacts, such as following dumping and bilge water regulations."
      )
    ),
    
    paste(
      p(
        strong("Compensation."),
        "Compensation includes mitigation practices that involve offsetting an impact through financial means or by restoration, enhancement, or other conservation measures."
      )
    ),
    
    paste(
      p(
        strong("Turbine Operation Parameters."),
        "Turbine operation parameters include mitigation practices that focus on movement of turbines (e.g., increased cut-in speed to avoid bats)."
      )
    ),
    
    paste(
      p(
        strong("Curtailment"),
        "Curtailment is not included in this category as it is considered a shutdown/low power mitigation practice."
      )
    ),
    
    paste(
      p(
        strong("Deterrence/Attraction Reduction."),
        "Deterrence/attraction reduction mitigation practices include efforts to actively discourage animals from approaching activities and/or structures (e.g., use of pingers) or reduce the attractiveness of activities or structures (e.g., avoid including nesting habitat on turbines, use colors not attractive to birds). This does not include choices in lighting meant to reduce attraction, which is considered a lighting alternative mitigation practice."
      )
    ),
    
    paste(
      p(
        strong("Lighting Alternatives."),
        "Lighting alternatives mitigation practices include choices in lighting that can minimize attraction or deter animals, including considerations like number and intensity of lights, lighting color, and periodicity."
      )
    ),
    
    paste(
      p(
        strong("Engagement/Communication."),
        "Engagement/communication mitigation practices include outreach efforts, information sharing, research facilitation, and other efforts to inform and learn from stakeholders in ways that will minimize and avoid impacts of offshore wind energy development."
      )
    ),
    
    paste(
      p(
        strong("Monitoring."),
        "Monitoring includes mitigation practices that observe and evaluate potential impacts to inform decisions and adapt management practices (e.g., measuring the numbers of marine mammals or birds traveling through an area to inform siting or mitigation actions). mitigation practices categorized as monitoring do not include any specific mitigation actions. Rather, specific actions are included in other generalized mitigation practices. For example, clearance for marine mammals prior to starting pile driving is a shutdown/low-power action, or turning on a deterrence device when birds are detected by a monitoring device is a deterrence/attraction reduction action."
      )
    ),
    
    paste(
      p(
        strong("Fisheries Safety."),
        "Fisheries safety mitigation practices are direct actions to reduce hazards of offshore wind energy development to increase safety of people and vessels (e.g., safety protocols for designating vessel right-of-way, marking designated transit zones, and infrastructure modifications to improve offshore communication and reduce interference with navigational equipment). This does not include outreach, research, and information sharing efforts, which are considered engagement/communication mitigation practices."
      )
    )
  )

